### ISSUE TITLE
Bill S Preston, Esq.

### ISSUE THREAD

**Issue by tgines** [daniloq/rad-faces#3]
Minor change:
`Bill Esquire` should be `Bill Preston` since his name is _Bill S. Preston, Esq._

The "Esquire" part is just a suffix after his last name

👍  🥇

**Comment by daniloq** [comment]
@tgines You are 💯  right my friend. Like. I totally spaced on that one bruh. 

The fix is live! Thanks for checking out radfaces and for the righteous copy change.

![screen shot 2017-01-25 at 9 15 43 am](https://cloud.githubusercontent.com/assets/3597145/22293924/68564416-e2df-11e6-8a99-5a37e3984b89.png)

San Dimas High School football rules!
